version: "3.8"

volumes:
  meteo_data:

services:
  bot:
    image: registry.gitlab.com/aleksul/meteo-bot/bot
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
        window: 15s
      resources:
        limits:
          cpus: '0.75'
          memory: 60M
        reservations:
          cpus: '0.25'
          memory: 25M
    volumes:
        - meteo_data:/meteo_data
  meteo-collector:
    image: registry.gitlab.com/aleksul/meteo-bot/collector
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 20s
        max_attempts: 10
        window: 30s
      resources:
        limits:
          cpus: '0.25'
          memory: 30M
    volumes:
        - meteo_data:/meteo_data
